version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_project
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_demo
      MONGO_INITDB_ROOT_PASSWORD: admin_123
    volumes:
      - mongo-data:/data/db
      - image-data:/data/images

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_project
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_demo
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_123
      ME_CONFIG_BASICAUTH_USERNAME: mongo_demo_web
      ME_CONFIG_BASICAUTH_PASSWORD: web_123
    depends_on:
      - mongodb
  backend:
    build: ./backend
    container_name: flask_app_project
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
  image-data:
    driver: local
